version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: certs-ui
    ports:
      - "5000:5000" # not needed if you are using shared network
    volumes:
      - ./frontend/out:/app/static:ro
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=5000
    restart: unless-stopped

# uncomment the block below if both certs-ui and your web server both runs in a docker container
#    networks:
#      - shared-network
#
#networks:
#  shared-network:
#    name: shared-network   